### Oops  concept   
- python 
  - python is a programing paradism means it supports functiopn programming and object oriented programming and also works with procedure oriented programming
- procedure oriented language  
  - procedure oriented means write our programming language using functions and objects and classes
- object oriented language  
  - object means real world entity or it is a physical entity represents the memory  
  - class means logical entity contains logic of the application


In [ ]:
# syntax for class::  
class class_name:
    variables  
    methods or function  
    

In [1]:
print(" hello")

 hello


In [2]:
4+7

11

In [4]:
class hi:
    a=10
    b=30
    name="apssdc"   
    def show():
        print("i am from show()function")

In [5]:
hi.name  

'apssdc'

In [7]:
hi.a

10

In [8]:
hi.b

30

In [9]:
hi.show()

i am from show()function


In [10]:
print(hi.a,hi.b)

10 30


In [12]:
class hi:
    name="apssdc"  
    program_name='python'  
    def display():
        print("i am from display function()") 
    def show():
        print("i am show function()")  
print(hi.name,hi.program_name)  
print(hi.display())

apssdc python
i am from display function()
None


In [15]:
print(hi.display())


i am from display function()
None


In [24]:
class Hello:
    def display():
        print("i am from display function()") 
        return("i am from return statement")
    def sh():
        print("i am show function()")    
print(Hello.display())  
print(Hello.sh())

i am from display function()
i am from return statement
i am show function()
None


In [ ]:
# IN JAVA OBJ DECLARATION  
  # CLASS_NAME OBJ_NAME=NEW CLASS_NAME
# IN PYTHON  
  # OBI_NAME=CLASS_NAME

In [26]:
class hi:
    name="apssdc"  
    program_name='python'  
    def display(self):
        print("i am from display function()") 
        return(" i am from return statement")
    def show():
        print("i am show function()")   
obj=hi() 
print(obj.name,obj.program_name)  
print(obj.display())

apssdc python
i am from display function()
 i am from return statement


### CONSRUTCOR 
- constructor:without using object we will call class function
  - in java::class name should be same as method name  
  - in python:: we will use one  special method to define consrtuctor  
  - __init(self)__

In [29]:
class hai:
    def __init__(self,name,roll_no):
        self.name=name
        self.roll_no=roll_no
        print("hi",self.name)
    def display(self):
        print("your roll_no",self.roll_no)  
obj=hai('manikanta','21A85A0606')
obj.display()

hi manikanta
your roll_no 21A85A0606


### Inheritance 
- inherits something parent class tp child class

In [ ]:
class A:
    #a,b=10,20
class B(A):
    #c,d=40,50
    

In [37]:
class A:
    a,b=10,20
    def msg():
        print("i am from class A")
class B(A):
    c,d=40,50
    def msg1():
        print("i am from class B")
obj=B
print(obj.c,obj.a)
obj.msg1()
obj.msg()

40 10
i am from class B
i am from class A


### PYTHON LIBRARIES FOR DATA SCIENCE
- to organize,processing,analyzing the huge amount of data
- apply data visualization  
- extracting the data from the source  
- nearly 20 python libraries are there 

top
- numpy
- pandas
- matplotlib  

### NUMPY  
- numpy::(num+py)means numerical data+python  
- it is fundamental for scientific computing  
- numpy is python library
- it is used to create multi-dimensional arrays for past operations
  - its dealing with mathematical,scientific staticsl data  
- numpy contains a powerful n dimensional array object which is in the form of rows and columns
- we can intilize numpy arrays from nested python lists

In [ ]:
# how to install numpy  
 - pip install numpy  

In [ ]:
# how to import and use numpy package 
import numpy as np

In [3]:
# how to find the numpy version
np.__version__  


'1.20.3'

In [2]:
# how to create numpy arrays
import numpy as np
a=np.array([1,2,3,4])# single dimesional number
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
a2=np.array([[2,3,4],[5,6,7,8]])
print(a2)
print(type(a2))

[list([2, 3, 4]) list([5, 6, 7, 8])]
<class 'numpy.ndarray'>


C:\Users\Lab\AppData\Local\Temp/ipykernel_5012/1131885264.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a2=np.array([[2,3,4],[5,6,7,8]])


In [9]:
a2=np.array([[1,2,3,4],[5,6,7,8]])
print(a2)
print(type(a2))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [10]:
a2.shape

(2, 4)

In [14]:
li=[1,2,3,'hi','i']
print(type(li))
a1=np.array(li)
print(a1)
print(type(a1))

<class 'list'>
['1' '2' '3' 'hi' 'i']
<class 'numpy.ndarray'>


In [15]:
a1=np.array([[1,2],[3,4],[5,6],[7,8]])
print(a1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
print(a1.dtype)

int32


In [20]:
b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [21]:
print(b.shape)

(2, 2)


In [22]:
b.itemsize

4

In [23]:
b.ndim

2

In [25]:
# range 
a=np.array(range(10))
print(a)
print(type(a))
print(a.shape)
print(a.size)
b=np.array(range(1,10,2))
print(b)
print(b.ndim)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)
10
[1 3 5 7 9]
1


In [26]:
 # resize of array(its modifies shape array itself)
a1=np.array([1,2,3,4,5,6,7,8])
print(a1)
print(a1.shape)
a1.resize(3)# resize the no of elements from original array 
print(a1)
print(a1.shape)
a1.resize(2,4)
print(a1)
print(a1.shape)
a1.resize(3,3)
print(a1)
print(a1.shape)

[1 2 3 4 5 6 7 8]
(8,)
[1 2 3]
(3,)
[[1 2 3 0]
 [0 0 0 0]]
(2, 4)
[[1 2 3]
 [0 0 0]
 [0 0 0]]
(3, 3)


In [29]:
# zero array  
import numpy as np
a1=np.zeros(3)
a2=np.zeros((2,4))
print(a1.dtype)
print(a2.dtype)
print(a1)
print(a2)

float64
float64
[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [30]:
# one array 
a2=np.ones(3,dtype="int64")
print(a2)
np.ones((6,5),dtype="int64")

[1 1 1]


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [32]:
# full array- full(dimesions,specified number)
a=np.full((3,3),7)
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [33]:
np.diag(a)

array([7, 7, 7])

In [34]:
np.full(3,100)

array([100, 100, 100])

In [35]:
np.full((3,9),500)

array([[500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500]])

In [36]:
# eye array  
np.eye(6,dtype="int64")

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]], dtype=int64)

In [38]:
n=np.eye(5)
n

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
np.diag(n)

array([1., 1., 1., 1., 1.])

In [40]:
r=np.random.randint(1,10)
r

6

In [41]:
s=np.random.randint(1,19,12).reshape(3,4)
s

array([[18, 13, 17, 17],
       [ 7, 12,  2, 16],
       [11, 16,  4,  8]])

In [42]:
p=np.random.random((6)).reshape(2,3)
p

array([[0.71147502, 0.94028153, 0.56728061],
       [0.21701061, 0.6436699 , 0.19820327]])

In [43]:
f=np.random.randn(2,3)
f

array([[ 0.19882272,  0.00184057,  0.1370105 ],
       [ 0.76908855, -0.08218397,  1.00177047]])

In [47]:
a=np.random.randint(1,30,(10,3))
a

array([[19,  7,  2],
       [ 7, 18,  6],
       [19, 21, 18],
       [ 1, 26,  8],
       [19, 20, 26],
       [ 7, 29, 17],
       [19, 17, 14],
       [22, 29, 10],
       [20, 24, 11],
       [ 9, 16, 17]])

In [48]:
a[1:5]

array([[ 7, 18,  6],
       [19, 21, 18],
       [ 1, 26,  8],
       [19, 20, 26]])

In [49]:
a[2:,:2]

array([[19, 21],
       [ 1, 26],
       [19, 20],
       [ 7, 29],
       [19, 17],
       [22, 29],
       [20, 24],
       [ 9, 16]])

In [50]:
a

array([[19,  7,  2],
       [ 7, 18,  6],
       [19, 21, 18],
       [ 1, 26,  8],
       [19, 20, 26],
       [ 7, 29, 17],
       [19, 17, 14],
       [22, 29, 10],
       [20, 24, 11],
       [ 9, 16, 17]])

In [51]:
a>10

array([[ True, False, False],
       [False,  True, False],
       [ True,  True,  True],
       [False,  True, False],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True],
       [False,  True,  True]])

In [52]:
a[a>10]

array([19, 18, 19, 21, 18, 26, 19, 20, 26, 29, 17, 19, 17, 14, 22, 29, 20,
       24, 11, 16, 17])

In [53]:
a[a>10].sum()

421

In [54]:
a.max()

29

In [55]:
a.min()

1

In [61]:
b=np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [63]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
print(a+b)
print("**************")
print(a-b)
print("________")
print(a*b)
print("$$$$$$$$$$$$$$$")
print(a%b)
print(np.max(a))
print(np.min(b))

[[10 12 14]
 [16 18 20]
 [22 24 26]]
**************
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
________
[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]
$$$$$$$$$$$$$$$
[[0 1 2]
 [3 4 5]
 [6 7 8]]
8
10


In [65]:
# 0 to 15-->(3,5)
a=np.arange(15).reshape(3,5)
print(a)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [66]:
print(np.mean(a))

7.0


In [67]:
b.dot(a)

array([[175, 208, 241, 274, 307],
       [220, 262, 304, 346, 388],
       [265, 316, 367, 418, 469]])

In [68]:
a+3

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17]])

In [69]:
a+10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
np.log(2)

0.6931471805599453

In [71]:
np.log([1,2,3])

array([0.        , 0.69314718, 1.09861229])

In [79]:
np.exp(1)

2.718281828459045

In [73]:
np.sin(0)

0.0

In [80]:
np.cos(1)

0.5403023058681397

In [75]:
np.tan(0)

0.0

In [81]:
import numpy
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

### PANDAS 
- pandas is the datascience package  
- it is used for  
  - data manipulation(modifications and updations)
  - data analysis  
  - data cleaning(to remove unnecessary data from data sets)
- contains  mainly two data structures in pandas
  - series-----sequence of data
  - data frames--data with row and column